"""Added stream video path

Revision ID: d154b06ed52f
Revises: 
Create Date: 2024-02-21 18:16:02.810030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd154b06ed52f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream_directory_path', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('stream_directory_path')

    # ### end Alembic commands ###
